import chokidar from "chokidar";
import { mkdirSync, cpSync, existsSync, rmSync, readdirSync } from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";

const SRC = "src";
const DOCS = "docs";

function ensureDirs() {
  mkdirSync(path.join(DOCS, "css"), { recursive: true });
  mkdirSync(path.join(DOCS, "js"), { recursive: true });
  mkdirSync(path.join(DOCS, "assets"), { recursive: true });
}

function copyFile(from, to) {
  ensureDirs();
  mkdirSync(path.dirname(to), { recursive: true });
  cpSync(from, to, { force: true });
}

function copyDir(from, to) {
  ensureDirs();
  mkdirSync(path.dirname(to), { recursive: true });
  cpSync(from, to, { recursive: true, force: true });
}

function removePath(p) {
  if (existsSync(p)) rmSync(p, { recursive: true, force: true });
}

function initialSync() {
  ensureDirs();

  for (const file of readdirSync(SRC)) {
    if (file.endsWith(".html")) {
      copyFile(path.join(SRC, file), path.join(DOCS, file));
    }
  }

  for (const file of ["robots.txt", "sitemap.xml", "site.webmanifest"]) {
    const from = path.join(SRC, file);
    if (existsSync(from)) {
      copyFile(from, path.join(DOCS, file));
    }
  }

  // Copy all content pages in subfolders (afspraak, tattoo-stijlen, etc.)
  for (const item of readdirSync(SRC, { withFileTypes: true })) {
    if (item.isDirectory() && item.name !== "js" && item.name !== "assets" && item.name !== "css") {
      copyDir(path.join(SRC, item.name), path.join(DOCS, item.name));
    }
  }

  copyDir(path.join(SRC, "js"), path.join(DOCS, "js"));
  copyDir(path.join(SRC, "assets"), path.join(DOCS, "assets"));
}

function toDocsPath(srcPath) {
  // src/xyz -> docs/xyz
  return path.join(DOCS, path.relative(SRC, srcPath));
}

ensureDirs();
initialSync();

// Tailwind watcher (dev: geen minify)
const tw = spawn(
  process.platform === "win32" ? "npm.cmd" : "npm",
  [
    "exec",
    "--",
    "tailwindcss",
    "-i",
    "./src/css/main.css",
    "-o",
    "./docs/css/main.css",
    "--postcss",
    "--watch",
  ],
  {
    stdio: "inherit",
    shell: process.platform === "win32", // belangrijk voor Windows + spaties in paden
  }
);

const watcher = chokidar.watch(SRC, { ignoreInitial: true });

function shouldCopyPath(p) {
  // Keep docs/css/main.css generated by Tailwind watcher only.
  return !p.includes(`${path.sep}css${path.sep}`);
}

watcher
  .on("add", (p) => {
    if (!shouldCopyPath(p)) return;
    const dest = toDocsPath(p);
    copyFile(p, dest);
  })
  .on("change", (p) => {
    if (!shouldCopyPath(p)) return;
    const dest = toDocsPath(p);
    copyFile(p, dest);
  })
  .on("unlink", (p) => {
    const dest = toDocsPath(p);
    removePath(dest);
  })
  .on("addDir", (p) => {
    const dest = toDocsPath(p);
    mkdirSync(dest, { recursive: true });
  })
  .on("unlinkDir", (p) => {
    const dest = toDocsPath(p);
    removePath(dest);
  });

// Netjes afsluiten
function shutdown(code = 0) {
  try {
    watcher.close();
  } catch { }
  try {
    tw.kill("SIGINT");
  } catch { }
  process.exit(code);
}

process.on("SIGINT", () => shutdown(0));
process.on("SIGTERM", () => shutdown(0));